--
title: "iccEpidatamodel"
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries}
library(dplyr)
require(MASS)
require(lubridate)
library(Epi)
```


```{r funciones}
## rec01 codifica >1=1####
rec01<-colwise(function(x){
  return(ifelse(x >1, 1, x))})  # codifica >1=1
## recn0 codifica <0=0####
recn0<-colwise(function(x){
  return(ifelse(x <0, 0, x))})  # codifica <0=0
## recna0 codifica na=0####
recna0<-colwise(function(x){
  return(ifelse(is.na(x), 0, x))})  # codifica na=0
```


```{r data}

# definiciones
https://docs.google.com/spreadsheets/d/1UgjUZ6antWgMZQ4zoGu9nlwDG7ngMqYvXQipLimCFNM/edit?ts=5a37ca71#gid=1745466320

# Setup -----
rm(list=ls())
setwd("~/Documents/Proyectos/osakidetza/icc/Datos proyecto ICC (bases madre)")

# Cargar los datos 
load("basal.rda")
load("ingresos_pri.rda")
load("outcome.rda")
# cargar el modelo (ya calculado)



outcome <- outcome %>% filter(!is.na(mort30))  # -10 casos?  se eliminan los que NO SE SABE SI fallece 30 dias despues del ingreso..!
basal <- basal %>% filter(id %in% outcome$id)  # nos quitamos poblacion xq no estan en el outcome? (nos quedamos sin fallecidos -supongo que son inmediatos-)
ingresos_pri <- ingresos_pri %>% filter(id %in% basal$id) 

# voy a pegar la primera fecha de ingreso postalta indice a la basal-> basalj.. con eso y censurando en diciembre 2015 (como no tenemos los ingresos 2016 -aunque tengamos los fallecimientos..-, para hacerlo cohorente, vamos a trabajar con 31-12-2015 como fin de estudio )

#Ingresos que son posteriores al alta
ingpost <- ingresos_pri %>% 
  filter(fing > falta_ing1, program == 0) %>% 
  mutate(dias_desde_alta = fing - falta_ing1) -> ingresos_post
# 

# sobre este ingresos_post, por un lado, recojo el detalle del reingreso mas cercano al indice, y por otro un resumen de la evolucion hasta el 12/2015: tiempo de exposicion, numero de ingresos...
# 
# names(ingpost)
# library(dplyr)
# # saco la primera [pero ya esta en outcomes!!]
# 
# ingepi0 <- group_by(ingpost, id)
# ingepi0 <- filter(ingepi0, rank(dias_desde_alta, ties.method="first")==1)
# (https://stackoverflow.com/questions/21308436/dplyr-filter-get-rows-with-minimum-of-variable-but-only-the-first-if-multiple)


basalj <- basal
rm(basal)
rm(ingresos_post, ingresos_pri)
# voy a cortar a diciembre 2015.. monto fcen
basalj$fcen <- ifelse(lubridate::year(basalj$fmort)<2016  & !is.na(basalj$fmort) ,basalj$fmort,as.Date("2015-12-31", "%Y-%m-%d"))

basalj$fcen <- as.Date(basalj$fcen, origin = "1970-01-01")

## voy a agregarle la fecha del primer ingreso (outcome como distancia) de diverso tipo...

names(outcome)
outj <- dplyr::select(outcome, id, fing1er, fing1er_ic, fing1er_peic)
rm(outcome)
basalj <- select(basalj,-c(uap,epi_unico,cie9_ing1))
basalj <- left_join(basalj,outj)
rm(outj)

# voy a extraer todos lo episodios de hospitalizacion tras el episodio indice -para construir un objeto con todos estos eventos usando cut de Epi (ver abajo)- en principio lo hare ON INGRESOS_ICC Y _CV _HPE (guardare el tipo)

names(ingpost)
ingpos3 <- dplyr::select(ingpost, id, fing, falta, hpe, ingreso_icc, ingreso_cv)
ingpos3 <- filter(ingpos3, ingreso_icc==1 | hpe==1 | ingreso_cv==1)
names(ingpos3)[6] <- "tipoi"
ingpos3$tipoi <- as.factor(ifelse(ingpos3$hpe==1,"3",
                        ifelse(ingpos3$ingreso_icc==1,"2","1")))
levels(ingpos3$tipoi) <- c("cv","icc_ine","icc_evi")
table(ingpos3$tipoi) 
ingpos3 <- dplyr::select(ingpos3,-c(hpe,ingreso_icc))


ingpos3 <- ingpos3 %>%
  arrange(id, fing) %>%
  group_by(id) %>%
  mutate(nh = 1:n()) %>% ungroup()

rm(ingpost)

```


```{r modelo en Epi}

# voy a cortar a diciembre 2015.. monto fcen
basalj$status <- ifelse(lubridate::year(basalj$fmort)<2016  & !is.na(basalj$fmort) ,1,0)

basalj <- dplyr::select(basalj,-c(causa,fmort, situ, fallecido))

# 
# basalj$fcen <- ifelse(lubridate::year(basalj$fmort)<2016  & !is.na(basalj$fmort) ,basalj$fmort,as.Date("2015-12-31", "%Y-%m-%d"))


iccL<- Lexis(entry=list(per=cal.yr(falta_ing1),  agein=edad_ing1),
            exit=list(per=cal.yr(fcen), age=cal.yr(fcen)-cal.yr(fec_nac)),
            exit.status=factor(status,labels=c("Alive","Death")),data=dplyr::select(basalj,id,sexo,indice_medea,comarca,falta_ing1,fcen,fec_nac,fing1er,fing1er_ic,fing1er_peic, status, edad_ing1))


summary(iccL)
# 
# Transitions:
#      To
# From    Alive Death  Records:  Events: Risk time:  Persons:
#   Alive  9313  6127     15440     6127    9531029     15440
# 


plot(iccL,xlim=c(2011,2016),type="b" )  # ??
points( iccL,  col="red", cex=1.5 )
 
# me quedo con fecha de ingreso

 # Multiple events of the same type (recurrent events)
 ## COMO HA DE SER ESTE DATA.FRAME DE ENTRADA?
 
#  The cutLexis function allows a number of different ways of specifying the cutpoints and of modifying the status variable.
# If the cut argument is a dataframe it must have columns lex.id, cut and new.state. The values of lex.id must be unique. In this case it is assumed that each row represents a cutpoint (on the timescale indicated in the argument timescale). This cutpoint will be applied to all records in data with the corresponding lex.id. This makes it possible to apply cutLexis to a split Lexis object.
# If a new.state argument is supplied, the status variable is only modified at the time of the cut point.
# However, it is often useful to modify the status variable after the cutpoint when an important event occurs. There are three distinct ways of doing this.
# If the progressive=TRUE argument is given, then a "progressive" model is assumed, in which the status can either remain the same or increase during follow-up, but never decrease. This assumes that the state variables lex.Cst and lex.Xst are either numeric or ordered factors. In this case, if new.state=X, then any exit status with a value less than X is replaced with X. The Lexis object must already be progressive, so that there are no rows for which the exit status is less than the entry status. If lex.Cst and lex.Xst are factors they must be ordered factors if progressive=TRUE is given.
 
ingpos4 <- inner_join(ingpos3,dplyr::select(iccL,lex.id,id))
rm(ingpos3)

names(ingpos4)[2] <- "cut"
ingpos4$cut <- cal.yr(ingpos4$cut)
ingpos4$new.state <- 1


iccC <- iccL

 for(n in 1:20 ) # hay hasta 20 hospitalizaciones
 {iccC <- cutLexis(data=iccC, cut=subset(ingpos4,nh==n), "per", count=TRUE )}

## quiero añadir al objeto tipoi y nh
names(ingpos4)[2] <- "per"
iccC2 <- left_join(iccC,dplyr::select(ingpos4,-c(new.state)))

 View(dplyr::select(iccC2,-c(sexo:edad_ing1)))
names(ingpos4)

rm(ingpos4, iccC)
rm(basalj)
rm(n)

)# Splitting the follow-up time along a timescale

# iccS1 <- splitLexis( iccL, "agein", breaks=c(50,60,70,80,90) )
#  summary( iccL )
# iccS2 <- splitLexis( iccS1, "per", breaks=seq(2011,2016,1) )
#  summary( iccS2 )
# 
# names(iccL) 

 

```
  
 
                
                
```{r rstudio github}


http://www.molecularecologist.com/2013/11/using-github-with-r-and-rstudio/
http://r-bio.github.io/intro-git-rstudio/
https://jennybc.github.io/2014-05-12-ubc/ubc-r/session03_git.html
https://www.r-bloggers.com/rstudio-and-github/
https://support.rstudio.com/hc/en-us/articles/200532077-Version-Control-with-Git-and-SVN

# git remote rm origen
# git remote rm destination

# git remote add origin https://github.com/jujulijuli/icc.git
# git config remote.origin.url git@github.com:ewenharrison/test.git
# git pull -u origin master
git push -u origin master

https://stackoverflow.com/questions/10298291/cannot-push-to-github-keeps-saying-need-merge
git push -f # force
```

